build:
  image: arm32v7/golang:1.8
  pull: true
  commands:
    - git clone https://github.com/sass/libsass.git /libsass
    - git clone https://github.com/sass/sassc.git /gopath1.5/src/github.com/sass/sassc
    - export SASS_LIBSASS_PATH=/libsass
    - cd /gopath1.5/src/github.com/sass/sassc
    - make
    - cp bin/sassc /usr/local/bin/
    # - go get -d github.com/dchest/jsmin
    # - go get -d github.com/eknkc/amber
    # - go get -d github.com/go-swagger/go-swagger/spec
    # - go get -d github.com/PuerkitoBio/goquery
    # - go get -d github.com/russross/blackfriday
    # - go get -d github.com/PuerkitoBio/purell
    # - go get -d github.com/drone/drone
    # - cd /gopath1.5/src/github.com/drone/drone
    - mkdir -p $GOPATH/src/github.com/drone
    - cd $GOPATH/src/github.com/drone/
    - git clone https://github.com/drone/drone
    - cd drone
    - make deps gen
    - make build
    - mkdir -p /data/usr/local/bin/
    - cp drone/drone /data/usr/local/bin/drone
    - chmod a+x /data/usr/local/bin/drone
    - cp --parents /etc/ssl/certs/ca-certificates.crt /data/
    - mv /data /drone/src/github.com/armdrone/drone/data
 

