debug: true

build:
  image: hypriot/rpi-golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - apt-get update
    - apt-get install -y mercurial g++ libsqlite3-dev ca-certificates

